// src/utils/logoHardcoded.js
/**
 * Hardcoded domain/logo mappings for companies in the user-provided list.
 * This ensures strict logo association by mapping company names to their primary domains or direct logo URLs.
 * Part 1: Companies starting with A-B
 */

export const HARDCODED_LOGOS = {
    // Top 5 Parent Brands (Strict)
    "Google": "https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_92x30dp.png",
    "Google DeepMind": "https://deepmind.google/favicon.ico",
    "Amazon": "https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg",
    "Amazon Web Services (AWS)": "https://upload.wikimedia.org/wikipedia/commons/9/93/Amazon_Web_Services_Logo.svg",
    "Apple": "https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg",
    "Meta": "https://upload.wikimedia.org/wikipedia/commons/7/7b/Meta_Platforms_Inc._logo.svg",
    "Microsoft": "https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg",

    // User Provided List - A & B (Batch 1)
    "{devlogic}": "devlogic.io",
    "1stDibs": "1stdibs.com",
    "1Phi Inc": "1phi.ai",
    "AAM - American Axle & Manufacturing": "aam.com",
    "Abaka AI": "abaka.ai",
    "Abbott": "abbott.com",
    "AbbVie": "abbvie.com",
    "Abridge": "abridge.com",
    "Appleton Finn": "appletonfinn.com",
    "Access Healthcare": "accesshealthcare.com",
    "Accion Labs": "accionlabs.com",
    "ACCIONA": "acciona.com",
    "Accrue": "accrue.com",
    "Acetech Group Corporation": "acetech.com",
    "Acezd": "acezd.com",
    "AcuityMD": "acuitymd.com",
    "Adaptec Solutions": "adaptec.com",
    "Adaptive ML": "adaptive.ai",
    "Adyen": "adyen.com",
    "AECOM": "aecom.com",
    "Airbnb": "airbnb.com",
    "Airbyte": "airbyte.com",
    "Alation": "alation.com",
    "Bayer": "bayer.com",
    "Alcoa": "alcoa.com",
    "Alcon": "alcon.com",
    "Alibaba Group": "alibaba.com",
    "AlixPartners": "alixpartners.com",
    "Alkami Technology": "alkami.com",
    "Alkermes": "alkermes.com",
    "Allegiant": "allegiantair.com",
    "Amazon Web Services (AWS)": "aws.amazon.com",
    "AMD": "amd.com",
    "American Express": "https://upload.wikimedia.org/wikipedia/commons/3/30/American_Express_logo.svg",
    "Americold Logistics, LLC": "americold.com",
    "AMETEK": "ametek.com",
    "Amica Insurance": "amica.com",
    "Ampa": "ampa.com",
    "Amphenol": "amphenol.com",
    "Anagh Technologies Inc": "anaghtech.com",
    "Analysis Group": "analysisgroup.com",
    "Anchorage Digital": "anchorage.com",
    "Anduril Industries": "anduril.com",
    "Anthropic": "https://s.yimg.com/zb/imgv1/96da9ece-4eee-3ce8-95b6-a49550964b21/t_140x140",
    "AOI": "aoi-inc.com",
    "Apple": "apple.com",
    "Applied Materials": "appliedmaterials.com",
    "Arcadis": "arcadis.com",
    "Archer": "archer.com",
    "Arctic Wolf": "arcticwolf.com",
    "Arista Networks": "arista.com",
    "Arm": "arm.com",
    "Arrow Electronics": "arrow.com",
    "Articulate": "articulate.com",
    "Arup": "arup.com",
    "Assembled": "assembled.com",
    "Astera Institute": "astera.org",
    "Astera Labs": "asteralabs.com",
    "AstraZeneca": "astrazeneca.com",
    "ASUS": "asus.com",
    "athenahealth": "athenahealth.com",
    "Atlantic Container Line": "aclcargo.com",
    "Atlassian": "atlassian.com",
    "Attentive": "attentive.com",
    "Audible": "audible.com",
    "Autodesk": "autodesk.com",
    "Avalara": "avalara.com",
    "Axway": "axway.com",
    "Baanyan Software Services, Inc.": "baanyan.com",
    "BAE Systems": "baesystems.com",
    "Bank of America": "bankofamerica.com",
    "Barclays": "barclays.com",
    "Bayer": "bayer.com",
    "BCG": "bcg.com",
    "BD": "bd.com",
    "Bechtel": "bechtel.com",
    "Benchstack Ai": "benchstack.ai",
    "BILL": "bill.com",
    "Bitsight": "bitsight.com",
    "Black & Veatch": "bv.com",
    "Block": "block.xyz",
    "BNSF Railway": "bnsf.com",
    "BNY": "bnymellon.com",
    "Boehringer Ingelheim": "boehringer-ingelheim.com",
    "Booking Holdings": "bookingholdings.com",
    "Booz Allen Hamilton": "boozallen.com",
    "Bosch": "bosch.com",
    "Boston Consulting Group (BCG)": "bcg.com",
    "Bounteous": "bounteous.com",
    "Bridgewater Associates": "bridgewater.com",
    "Bright Vision Technologies": "bvteck.com",
    "Bristol Myers Squibb": "bms.com",
    "Broadcom": "broadcom.com",
    "Bruker": "bruker.com",
    "Capital One": "https://upload.wikimedia.org/wikipedia/commons/9/98/Capital_One_logo.svg",
    "CareerWellness": "careerwellness.co",
    "Cartesia": "cartesia.ai",
    "CHEManager International": "chemanager-online.com",
    "Clera": "clera.com",
    "CVector Energy": "cvector.com",
    "Cyient": "cyient.com",
    "DATARA": "datara.io",
    "Delta System & Software, Inc.": "deltasystech.com",
    "European Tech Recruit": "european-techrecruit.com",
    "Fix-It 24/7": "fixit247.com",
    "GLASS Imaging": "glassimaging.com",
    "Global Lehman Consulting": "global-lehman.com",
    "Golden Meadow Investment LLC": "goldenmeadowinvestment.com",
    "Ground Truth Analytics": "groundtruthanalytics.com",
    "Hamilton Barnes 🌳": "hamilton-barnes.com",
    "Hi Labs": "hilabs.com",
    "HireIO, Inc.": "hireio.com",
    "Hyundai America Technical Center, Inc. (HATCI)": "hatci.com",
    "IDB Invest": "idbinvest.org",
    "IM Global LLC": "imgloballlc.com",
    "IM Global": "imgloballlc.com",
    "Imetris Corporation": "imetris.com",
    "IMI": "imiplc.com",
    "Inflection AI": "inflection.ai",
    "Investigo": "investigo.co.uk",
    "Latitude AI": "lat.ai",
    "Lumicity": "lumicity.io",
    "Neuberger Berman": "nb.com",
    "Palo Alto Networks": "paloaltonetworks.com",
    "Verkada": "verkada.com",
    "VOYA Visa Technology": "voya.com",
    "Zurich North America": "zurichna.com",
    "3E": "3eco.com",
    "Acro Service Corp": "acrocorp.com",
    "Acumenz Consulting": "acumenz.com",
    "Acumenz": "acumenz.com",
    "Agave": "agaveapi.com",

    // User Provided List - C to G (Batch 2)
    "C1": "c1.com",
    "Caddie AI": "caddie.ai",
    "Caesars Sportsbook & Casino": "caesars.com",
    "Calendly": "calendly.com",
    "CalPortland": "calportland.com",
    "Canva": "canva.com",
    "Capco": "capco.com",
    "Capital One": "https://upload.wikimedia.org/wikipedia/commons/9/98/Capital_One_logo.svg",
    "CARFAX": "carfax.com",
    "Cargill": "cargill.com",
    "CarMax": "carmax.com",
    "Carvana": "carvana.com",
    "Cash App": "cash.app",
    "Caterpillar": "caterpillar.com",
    "CDK Global": "cdkglobal.com",
    "Chainalysis": "chainalysis.com",
    "CHANEL": "chanel.com",
    "Charles River Associates": "crai.com",
    "Checkmarx": "checkmarx.com",
    "Chewy": "chewy.com",
    "Cisco": "cisco.com",
    "Citadel Securities": "citadel.com",
    "CitiusTech": "citiustech.com",
    "ClickUp": "clickup.com",
    "Cloudera": "cloudera.com",
    "Cohesity": "cohesity.com",
    "Collabera": "collabera.com",
    "Collibra": "collibra.com",
    "Comcast": "comcast.com",
    "Continental": "continental.com",
    "Cornerstone Research": "cornerstone.com",
    "Corning Incorporated": "corning.com",
    "Costain Group PLC": "costain.com",
    "Credit One Bank": "creditonebank.com",
    "Cricut": "cricut.com",
    "Cummins": "cummins.com",
    "CVS Health": "cvshealth.com",
    "Cyient": "cyient.com",
    "D-Wave": "dwavesys.com",
    "D. E. Shaw Research": "deshawresearch.com",
    "Dart Container": "dartcontainer.com",
    "Dassault Systèmes": "3ds.com",
    "dbt Labs": "getdbt.com",
    "Deel": "deel.com",
    "Deepgram": "deepgram.com",
    "Dell Technologies": "dell.com",
    "Deloitte": "deloitte.com",
    "DENSO": "denso.com",
    "Deutsche Bank": "db.com",
    "Discord": "discord.com",
    "Docker, Inc": "docker.com",
    "Dominion Energy": "dominionenergy.com",
    "DPR Construction": "dpr.com",
    "Drata": "drata.com",
    "DXC Technology": "dxc.com",
    "EAB": "eab.com",
    "Eaton": "eaton.com",
    "Ecolab": "ecolab.com",
    "EDF": "edf.fr",
    "Eightfold AI": "eightfold.ai",
    "Electronic Arts (EA)": "ea.com",
    "ElevenLabs": "elevenlabs.io",
    "EliseAI": "eliseai.com",
    "Emerson": "emerson.com",
    "Emirates": "emirates.com",
    "Equifax": "equifax.com",
    "Ericsson": "ericsson.com",
    "Esri": "esri.com",
    "Etsy": "etsy.com",
    "Eurofins": "eurofins.com",
    "Evercore": "evercore.com",
    "Eversource Energy": "eversource.com",
    "Expedia Group": "expediagroup.com",
    "Exterest": "exterest.com",
    "EY": "ey.com",
    "FactSet": "factset.com",
    "Fanatics": "fanatics.com",
    "FanDuel": "fanduel.com",
    "Fastly": "fastly.com",
    "FDM Group": "fdmgroup.com",
    "Fidelity Investments": "fidelity.com",
    "Fifth Third Bank": "53.com",
    "Flex": "flex.com",
    "Flock Safety": "flocksafety.com",
    "FMC Corporation": "fmc.com",
    "Ford Motor Company": "ford.com",
    "Formlabs": "formlabs.com",
    "Fractal": "fractal.ai",
    "Franklin Templeton": "franklintempleton.com",
    "Freddie Mac": "freddiemac.com",
    "Freeport-McMoRan": "fcx.com",
    "Fujitsu": "fujitsu.com",
    "GE Aerospace": "geaerospace.com",
    "GE HealthCare": "gehealthcare.com",
    "GE Vernova": "gevernova.com",
    "GEICO": "geico.com",
    "Genentech": "gene.com",
    "Genpact": "genpact.com",
    "Gensyn": "gensyn.ai",
    "Genworth": "genworth.com",
    "GitLab": "gitlab.com",
    "Glean": "glean.com",
    "GlobalFoundries": "gf.com",
    "Goldman Sachs": "goldmansachs.com",
    "Google": "google.com",
    "Google DeepMind": "deepmind.google",
    "Greenhouse Software": "greenhouse.io",
    "Greystar": "greystar.com",
    "Gulfstream Aerospace": "gulfstream.com",

    // User Provided List - H to Z (Final Batch)
    "H-E-B": "heb.com",
    "HARMAN": "harman.com",
    "HCLTech": "hcltech.com",
    "Hewlett Packard Enterprise": "hpe.com",
    "Hitachi": "hitachi.com",
    "Honeywell": "honeywell.com",
    "HP": "hp.com",
    "HSBC": "hsbc.com",
    "HubSpot": "hubspot.com",
    "Hyundai": "hyundai.com",
    "IBM": "ibm.com",
    "Infosys": "https://upload.wikimedia.org/wikipedia/commons/9/95/Infosys_logo.svg",
    "Intel Corporation": "intel.com",
    "Intuit": "https://upload.wikimedia.org/wikipedia/commons/e/e0/Intuit_logo.svg",
    "IQVIA": "iqvia.com",
    "J.P. Morgan": "jpmorgan.com",
    "JPMorgan Chase": "jpmchase.com",
    "John Deere": "deere.com",
    "Johnson & Johnson": "jnj.com",
    "Johnson Controls": "johnsoncontrols.com",
    "Juniper Networks": "juniper.net",
    "Kellogg": "kelloggcompany.com",
    "KPMG": "kpmg.com",
    "Kodiak": "kodiak.ai",
    "Kodiak Robotics": "kodiak.ai",
    "Kohler Ventures": "kohlerventures.com",
    "Kraft Heinz": "kraftheinzcompany.com",
    "L3Harris": "l3harris.com",
    "Lamb Weston": "lambweston.com",
    "Leidos": "leidos.com",
    "Lenovo": "lenovo.com",
    "Liberty Mutual": "libertymutual.com",
    "LinkedIn": "linkedin.com",
    "Lockheed Martin": "lockheedmartin.com",
    "Lowe's": "lowes.com",
    "Lululemon": "lululemon.com",
    "Macy's": "macys.com",
    "Marriott International": "marriott.com",
    "Mars": "mars.com",
    "Mastercard": "mastercard.com",
    "McDonald's": "mcdonalds.com",
    "McKesson": "mckesson.com",
    "Medtronic": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Medtronic_logo.svg/512px-Medtronic_logo.svg.png",
    "Merck": "merck.com",
    "Meta": "meta.com",
    "Microsoft": "microsoft.com",
    "Moderna": "modernatx.com",
    "Morgan Stanley": "morganstanley.com",
    "Motorola Solutions": "motorolasolutions.com",
    "Netflix": "netflix.com",
    "New York Life": "newyorklife.com",
    "Nike": "nike.com",
    "Northrop Grumman": "northropgrumman.com",
    "NVIDIA": "nvidia.com",
    "NXP Semiconductors": "nxp.com",
    "Oracle": "oracle.com",
    "Otis Worldwide": "otis.com",
    "Palo Alto Networks": "paloaltonetworks.com",
    "PayPal": "paypal.com",
    "PepsiCo": "pepsico.com",
    "Pfizer": "pfizer.com",
    "Pinterest": "pinterest.com",
    "PNC Financial Services": "pnc.com",
    "PricewaterhouseCoopers (PwC)": "pwc.com",
    "Procter & Gamble": "pg.com",
    "Prudential Financial": "prudential.com",
    "Qualcomm": "qualcomm.com",
    "Raytheon Technologies": "rtx.com",
    "Reddit": "reddit.com",
    "Regeneron": "regeneron.com",
    "Reliance Industries": "ril.com",
    "ResMed": "resmed.com",
    "Rivian": "rivian.com",
    "Roche": "roche.com",
    "Rockwell Automation": "rockwellautomation.com",
    "Salesforce": "salesforce.com",
    "Samsung": "samsung.com",
    "Sanofi": "sanofi.com",
    "SAP": "sap.com",
    "Schneider Electric": "se.com",
    "ServiceNow": "servicenow.com",
    "Shell": "shell.com",
    "Siemens": "siemens.com",
    "Snap Inc.": "snap.com",
    "Snowflake": "snowflake.com",
    "Sony": "sony.com",
    "SpaceX": "spacex.com",
    "Splunk": "splunk.com",
    "Spotify": "spotify.com",
    "Square": "squareups.com",
    "Starbucks": "starbucks.com",
    "State Farm": "statefarm.com",
    "Stripe": "stripe.com",
    "Subaru": "subaru.com",
    "Superhuman": "superhuman.com",
    "Synopsys": "synopsys.com",
    "Systems Technology Group, Inc. (STG)": "stgit.com",
    "T-Mobile": "t-mobile.com",
    "Target": "target.com",
    "Tesla": "tesla.com",
    "Texas Instruments": "ti.com",
    "Thermo Fisher Scientific": "thermofisher.com",
    "TikTok": "tiktok.com",
    "TJX Companies": "tjx.com",
    "Toyota": "toyota.com",
    "Twilio": "twilio.com",
    "Uber": "uber.com",
    "Ubisoft": "ubisoft.com",
    "Under Armour": "underarmour.com",
    "United Airlines": "united.com",
    "UnitedHealth Group": "unitedhealthgroup.com",
    "UPS": "ups.com",
    "U.S. Bank": "usbank.com",
    "Valeant Pharmaceuticals": "bauschhealth.com",
    "Vanguard": "vanguard.com",
    "Verizon": "verizon.com",
    "Vertex Pharmaceuticals": "vrtx.com",
    "Visa": "visa.com",
    "VMware": "vmware.com",
    "Volkswagen": "volkswagen.com",
    "Walgreens": "walgreens.com",
    "Walmart": "walmart.com",
    "Warner Bros. Discovery": "wbd.com",
    "Wayfair": "wayfair.com",
    "Wells Fargo": "wellsfargo.com",
    "Western Digital": "wdc.com",
    "Wipro": "wipro.com",
    "Workday": "workday.com",
    "Xerox": "xerox.com",
    "Yelp": "yelp.com",
    "Zillow": "zillow.com",
    "Zoom": "zoom.us",
    "Zoox": "zoox.com",
    "Zscaler": "zscaler.com"

};

/**
 * Returns a hardcoded logo URL or domain for a company.
 * If the value is a domain (no http), it will be converted to a favicon URL.
 */
export const getHardcodedLogo = (name) => {
    if (!name) return null;
    let logo = HARDCODED_LOGOS[name];

    // Improved matching: Alpha-numeric only comparison for highly reliable matching
    if (!logo) {
        const cleanName = name.toLowerCase().replace(/[^a-z0-9]/g, '');
        // Sort keys by length descending so that the most specific match wins (e.g. "Amazon Web Services" beats "Amazon")
        const sortedEntries = Object.entries(HARDCODED_LOGOS).sort((a, b) => b[0].length - a[0].length);
        
        const entry = sortedEntries.find(([k]) => {
            const cleanKey = k.toLowerCase().replace(/[^a-z0-9]/g, '');
            if (cleanKey.length < 3) return false;
            
            // Priority 1: Exact Match (High Confidence)
            if (cleanName === cleanKey) return true;
            
            // Priority 2: Full Word Match (Only if key is significant)
            // This prevents "Appleton" matching "Apple" but allows "Microsoft Corp" to match "Microsoft"
            if (cleanKey.length >= 4 && cleanName.startsWith(cleanKey)) {
                // Check if the next character in the original name is a space or separator
                // (This is a bit hard with cleanName, so let's stick to a safer length-based heuristic)
                // If the key is 'apple' and name is 'appleton', length difference is small but it's a different word.
                // If the key is 'microsoft' and name is 'microsoft corp', that's usually a match.
                
                // Let's use a stricter rule: if the key is a major brand (short), only exact match.
                const majorBrands = ['apple', 'meta', 'google', 'amazon', 'adobe', 'intel', 'tesla', 'netflix', 'uber', 'lyft'];
                if (majorBrands.includes(cleanKey)) return cleanName === cleanKey;
                
                return true; 
            }
            
            return false;
        });
        if (entry) logo = entry[1];
    }

    if (!logo) return null;

    if (logo.startsWith('http')) return logo;
    return `https://www.google.com/s2/favicons?domain=${logo}&sz=128`;
};
